//! 构建期生成 `embedded.rs`：把 `assets/embed/` 下**已就位**的内置扩展 exe
//! 以 `include_bytes!` 内嵌进宿主。产物即单文件 `dd-run.exe`。
//!
//! 目录约定：
//! - `assets/embed/` 由 [`tools/package.sh`](../../tools/package.sh) 在宿主编译前生成
//!   （先 `cargo build -p dd-ext --release`，再把 5 个 `dd-ext-*.exe` 拷入本目录）。
//! - **开发期**（`cargo test` / 直接 `cargo build`，未经 package.sh）该目录为空 →
//!   生成的 `EMBEDDED` 为空切片 → 运行回退到「exe 同目录发现」路径（原行为不变）。
//!
//! 内嵌集合必须与 `crates/dd-host/src/builtin.rs` 的 `BUILTINS`（5 个内置扩展
//! 的可执行名）保持一致，防止宿主注册了「未被内嵌」的扩展。

use std::env;
use std::fs;
use std::path::PathBuf;

/// 内嵌的内置扩展可执行名（与 `dd-host::builtin::BUILTINS[*].exe` 对齐）。
const EMBED_EXES: [&str; 5] = [
    "dd-ext-apps",
    "dd-ext-calc",
    "dd-ext-system",
    "dd-ext-websearch",
    "dd-ext-shell",
];

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let embed_dir = manifest_dir.join("assets").join("embed");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let gen = out_dir.join("embedded.rs");

    let mut code = String::new();
    code.push_str(
        "// @generated by build.rs — 不要手改。内嵌内置扩展 exe（package.sh 先构建 dd-ext\n\
         // 再拷入 assets/embed；开发期目录为空 → 下表为空 → 运行回退 exe 同目录发现）。\n",
    );
    code.push_str("#[allow(dead_code)]\n");
    code.push_str("/// 内嵌扩展：`(可执行文件名, 字节)`。开发期可能为空切片。\n");
    code.push_str("pub const EMBEDDED: &[(&str, &[u8])] = &[\n");

    let mut found: Vec<String> = Vec::new();
    for exe in EMBED_EXES {
        let fname = if cfg!(windows) {
            format!("{exe}.exe")
        } else {
            exe.to_string()
        };
        let p = embed_dir.join(&fname);
        if p.is_file() {
            // include_bytes 的相对路径基于「包含该宏的源文件」（即本生成文件，位于
            // OUT_DIR）；故这里直接用绝对路径最稳妥（Rust include_bytes 接受绝对路径）。
            // 注意：不要 canonicalize()——Windows 会返回 `\\?\C:\...` 前缀，include_bytes
            // 打不开；manifest_dir 已是绝对路径，直接拼接即可。
            let lit = p.display().to_string().replace('\\', "\\\\");
            code.push_str(&format!("    (\"{fname}\", include_bytes!(\"{lit}\")),\n"));
            found.push(fname);
        }
    }
    code.push_str("];\n");
    fs::write(&gen, code).expect("写 embedded.rs");

    // 让 package.sh 刷新 embed 目录后能触发宿主重编译（重内嵌）。
    println!("cargo:rerun-if-changed={}", embed_dir.display());
    println!("cargo:rerun-if-env-changed=CARGO_MANIFEST_DIR");
    eprintln!(
        "[build.rs] dd-gui 内嵌扩展 {} 个：{}",
        found.len(),
        if found.is_empty() {
            "（空：回退 exe 同目录发现；经 tools/package.sh 构建才有内嵌）".to_string()
        } else {
            found.join(", ")
        }
    );
}
