//! 构建期生成 `embedded.rs`：M9 起**不再内嵌内置扩展**，本表恒为空，
//! 运行期 `EMBEDDED` 为空切片 → 不走「exe 内嵌物化」路径（原「exe 同目录发现」/
//! sidecar 路径保留）。
//!
//! 目录约定：
//! - `assets/embed/` 由 [`tools/package.sh`](../../tools/package.sh) 维护。M9 起
//!   该目录不再放入内置 exe（`package.sh` 已移除拷贝步骤），故 `EMBEDDED` 恒为空。
//! - **仅将来若要内嵌某 sidecar**（如文件搜索 `dd-ext-search`）才往 `EMBED_EXES`
//!   填条目；内置扩展一律 in-process（不 spawn、不内嵌，见
//!   `docs/m9-inprocess-builtins.md`）。
//!
//! 内嵌集合若恢复非空，须与 `crates/dd-host/src/builtin.rs` 的 `BUILTINS` 保持一致，
//! 防止宿主注册了「未被内嵌」的扩展。

use std::env;
use std::fs;
use std::path::PathBuf;

/// 内嵌的可执行名（M9 起**不再内嵌内置**；仅将来 sidecar 才填）。当前恒空。
const EMBED_EXES: &[&str] = &[];

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let embed_dir = manifest_dir.join("assets").join("embed");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let gen = out_dir.join("embedded.rs");

    let mut code = String::new();
    code.push_str(
        "// @generated by build.rs — 不要手改。M9 起内置扩展不再内嵌，本表恒为空；\n\
         // 仅将来内嵌 sidecar 时才会有条目。\n",
    );
    code.push_str("#[allow(dead_code)]\n");
    code.push_str("/// 内嵌扩展：`(可执行文件名, 字节)`。M9 起恒为空切片。\n");
    code.push_str("pub const EMBEDDED: &[(&str, &[u8])] = &[\n");

    let mut found: Vec<String> = Vec::new();
    for exe in EMBED_EXES {
        let fname = if cfg!(windows) {
            format!("{exe}.exe")
        } else {
            exe.to_string()
        };
        let p = embed_dir.join(&fname);
        if p.is_file() {
            // include_bytes 的相对路径基于「包含该宏的源文件」（即本生成文件，位于
            // OUT_DIR）；故这里直接用绝对路径最稳妥（Rust include_bytes 接受绝对路径）。
            // 注意：不要 canonicalize()——Windows 会返回 `\\?\C:\...` 前缀，include_bytes
            // 打不开；manifest_dir 已是绝对路径，直接拼接即可。
            let lit = p.display().to_string().replace('\\', "\\\\");
            code.push_str(&format!("    (\"{fname}\", include_bytes!(\"{lit}\")),\n"));
            found.push(fname);
        }
    }
    code.push_str("];\n");
    fs::write(&gen, code).expect("写 embedded.rs");

    // 让 package.sh 刷新 embed 目录后能触发宿主重编译（重内嵌）。
    println!("cargo:rerun-if-changed={}", embed_dir.display());
    println!("cargo:rerun-if-env-changed=CARGO_MANIFEST_DIR");
    eprintln!(
        "[build.rs] dd-gui 内嵌扩展 {} 个：{}",
        found.len(),
        if found.is_empty() {
            "（空：M9 起内置扩展不再内嵌；内置走 in-process，sidecar 经 dist/extensions.d/）"
                .to_string()
        } else {
            found.join(", ")
        }
    );
}
